
// Objective-C API for talking to the following Go packages
//
//	github.com/davidclarafigueiredo/SaleNotifier/appactions
//
// File is generated by gomobile bind. Do not edit.
#ifndef __NotifierLib_FRAMEWORK_H__
#define __NotifierLib_FRAMEWORK_H__

#include "Appactions.objc.h"
#include "Universe.objc.h"

#endif
