// Objective-C API for talking to github.com/davidclarafigueiredo/SaleNotifier/appactions Go package.
//   gobind -lang=objc github.com/davidclarafigueiredo/SaleNotifier/appactions
//
// File is generated by gobind. Do not edit.

#ifndef __Appactions_H__
#define __Appactions_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class AppactionsGameStruct;

@interface AppactionsGameStruct : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull nsuid;
@property (nonatomic) NSString* _Nonnull url;
@property (nonatomic) NSString* _Nonnull apiUrl;
@property (nonatomic) NSString* _Nonnull gameTitle;
@property (nonatomic) NSString* _Nonnull isDiscounted;
@property (nonatomic) NSString* _Nonnull regularPrice;
@property (nonatomic) NSString* _Nonnull discountedPrice;
@end

FOUNDATION_EXPORT NSString* _Nonnull AppactionsGetInformation(NSString* _Nullable url);

FOUNDATION_EXPORT void AppactionsRemoveEntryFromJSON(NSString* _Nullable jsonFileName, NSString* _Nullable nsuid);

FOUNDATION_EXPORT BOOL AppactionsUpdateJSONEntry(NSString* _Nullable jsonFileName, NSString* _Nullable url);

FOUNDATION_EXPORT void AppactionsWriteEntryToJSON(NSString* _Nullable jsonFileName, NSString* _Nullable url);

#endif
