// Objective-C API for talking to github.com/davidclarafigueiredo/SaleNotifier/appactions Go package.
//   gobind -lang=objc github.com/davidclarafigueiredo/SaleNotifier/appactions
//
// File is generated by gobind. Do not edit.

#ifndef __Appactions_H__
#define __Appactions_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT NSString* _Nonnull AppactionsGetInformation(NSString* _Nullable url);

#endif
